apiVersion: v1
kind: Service

metadata:
  name: crawler-mysql-svc
  namespace: tetragrama
  labels:
    app: crawler
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: crawler
    tier: mysql