apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: crawler-data-volume
  namespace: tetragrama
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
  storageClassName: manual
  volumeName: "mysql-pv002"
  selector:
    matchLabels:
      app: crawler
