apiVersion: v1
kind: Service

metadata:
  name: selenium-hub-svc
  namespace: tetragrama
  labels:
    app: selenium-hub
spec:
  type: ClusterIP
  ports:
  - name: hub
    port: 4444
    protocol: TCP
    targetPort: 4444
  selector:
    app: selenium-hub