apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: selenium-hub
  namespace: tetragrama
  labels:
    app: selenium-hub
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        image: selenium/hub:3.141.59-iron
        imagePullPolicy: Always
        ports:
        - containerPort: 4444
      nodeSelector:
        nodetype: apps