apiVersion: v1

kind: Service

metadata:
  name: repository-mysql-svc
  namespace: tetragrama

spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: repository-mysql
#    tier: mysql