apiVersion: extensions/v1beta1

kind: Deployment

metadata:
  name: repository-deployment
  namespace: tetragrama

spec:
  selector:
    matchLabels:
      app: repository
  #  replicas: 1
  #    revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: repository
    spec:
      containers:
        - name: repository
          image: <07-addr>
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: repository-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: repository-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: repository-config
                  key: SPRING_DATASOURCE_PASSWORD
          ports:
            - containerPort: 8080
              name: repository
      nodeSelector:
        nodetype: storage
      imagePullSecrets:
        - name: tetragrama-cred