apiVersion: v1

kind: Service

metadata:
  name: repository-svc
  namespace: tetragrama

spec:
  selector:
    app: repository
  type: NodePort
  ports:
    - port: 7001
      targetPort: 8080
      nodePort: 31120