apiVersion: extensions/v1beta1

kind: Deployment

metadata:
  name: repository-mysql-deployment
  namespace: tetragrama

spec:
  selector:
    matchLabels:
      app: repository-mysql
    #        tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: repository-mysql
    #        tier: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          resources:
            limits:
              cpu: "4"
            requests:
              cpu: "2"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
            - name: mysql-repository-data
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: repository-config
                  key: MYSQL_ROOT_PASSWORD
      nodeSelector:
        nodetype: storage
      volumes:
        - name: mysql-initdb
          configMap:
            name: repository-mysql-initdb-config
        - name: mysql-repository-data
          persistentVolumeClaim:
            claimName: repository-data-volume